-- Server-persisted per-user notifications for the bell + sidebar. Generated by request-flow
-- events (submit / approve / reject / issue / comment). readAt IS NULL means unread. tenantId is
-- kept so tenant deletion sweeps these up like every other tenant-scoped table.
CREATE TABLE "Notification" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "tenantId" TEXT,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "body" TEXT,
    "refType" TEXT,
    "refId" TEXT,
    "url" TEXT,
    "readAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "Notification_userId_readAt_idx" ON "Notification"("userId", "readAt");
CREATE INDEX "Notification_tenantId_idx" ON "Notification"("tenantId");
